version: 0.1

phases:
  install:
    commands:
      # - curl -o- -L https://yarnpkg.com/install.sh | bash
      - curl https://raw.githubusercontent.com/apex/apex/master/install.sh | sh
      - export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1 && npm install
      - cd ./functions/convert && export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1 && npm install
      # - ~/.yarn/bin/yarn
  # pre_build:
  #   commands:
  #     - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - apex deploy
  # post_build:
  #   commands:
  #     - npm run publish
  #     - apex deploy
# artifacts:
#   files:
#     - build/**/*
